# Generated by Django 2.0.2 on 2018-12-24 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181224_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='公開期限'),
        ),
    ]
