# Generated by Django 2.0.2 on 2018-12-30 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_date_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 0, 12, 5, 973893, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
