# Generated by Django 2.0.2 on 2019-01-21 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190112_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 8, 34, 4, 500057, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
