# Generated by Django 2.0.2 on 2019-01-23 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190121_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 0, 30, 16, 991529, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
