# Generated by Django 2.0.2 on 2019-01-24 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190123_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 2, 37, 43, 238363, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
