# Generated by Django 2.0.2 on 2019-01-26 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190124_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 3, 48, 29, 418237, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
