# Generated by Django 2.0.2 on 2019-01-27 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190127_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 7, 7, 44, 901044, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
