# Generated by Django 2.0.2 on 2019-01-28 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20190128_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 2, 14, 31, 544765, tzinfo=utc), verbose_name='公開期限'),
        ),
    ]
