# Generated by Django 2.0.2 on 2019-01-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190123_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='ファイル')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿リスト'},
        ),
    ]
