# Generated by Django 2.0.2 on 2019-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_good_plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
