# Generated by Django 2.0.2 on 2019-01-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20190127_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='food',
            new_name='good',
        ),
    ]
