# Generated by Django 2.0.2 on 2019-01-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190127_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='ファイル'),
        ),
    ]
